### ISSUE TITLE
OAM broken in SeaMonkey 2.46

### ISSUE THREAD

**Issue by JohnDDuncanIII** [Exalm/old-addon-manager#3]
Timestamp: 12/22/16, 12:29:52 PM
Error: TypeError: this.mControl is undefined
Source File: chrome://oam/content/extensions.xml
Line: 248

The line in question: 
248: else if (this.mControl.mAddon.install)

Seems as if an API change has, perhaps, removed or renamed the mControl variable. Not sure if you're still working on this, Exalm. If not, I will try to google around in search for a fix.

**Comment by alice-mkh** [comment]
Hello. No, I'm not working on it, sorry. I was doing a rewrite at some point, but stopped due to total lack of interest from anybody, including me. :)

**Comment by JohnDDuncanIII** [comment]
Darn, no worries; I will look into it. I hate the in-content addon manager. 

Seems as if the src tree still uses this stuff (https://dxr.mozilla.org/comm-central/source/mozilla/toolkit/mozapps/extensions/content/extensions.xml), which doesn't really explain why it's not working in 2.46... 

Anyway, I will look into it and add any fixes I find into my fork :D.

**Comment by alice-mkh** [comment]
I've checked and the rewrite code is in the repo. Feel free to continue it, it's not as terrible as the original version. :)

**Comment by JohnDDuncanIII** [comment]
Great! I will have a look.

**Comment by JohnDDuncanIII** [comment]
Hey, just wanted to let you know that I got this working with SeaMonkey 2.48 in my [fork](https://github.com/JohnDDuncanIII/old-addon-manager). There was a problem in the extensions.xml file, I believe.

**Comment by alice-mkh** [comment]
Well, see my reply above. :)
Additionally, since Mozilla wants to stop supporting XUL addons, I don't really think this addon has a future.
If you want to, I can just transfer you this repository and AMO listing.

**Comment by JohnDDuncanIII** [comment]
Great, I'd gladly take over. I will most likely be updating the extension until the XUL/XPCOM removal happens, so that makes the most sense :p

**Comment by alice-mkh** [comment]
Ok, will do it tomorrow. Send me an email about that.

**Comment by alice-mkh** [comment]
So?..

**Comment by JohnDDuncanIII** [comment]
Sure thing. You can transfer ownership of the repo, if you'd like.
